apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  # Updated 3 to 10 replices
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
